---
- hosts: servers
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Instalação do aptitude usando o apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Instação dos pacotes de sistema necessários
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Adicionando o Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adcionando o Repositorio do Docker
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Atualizando e Instalando o docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Instalando o Modulo do Docker
      pip:
        name: docker

    - name: Pull Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name:  Criando o Container HTTP e Expondo a Porta 8080
      command: docker run -dit --name httpd -p 8080:80 -v "$PWD":/usr/local/apache2/htdocs/ httpd:2.4